CREATE TABLE orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_no VARBINARY(64) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  quote_id BIGINT UNSIGNED NOT NULL,
  prepayment_id BIGINT UNSIGNED NOT NULL,
  payment_observation_id BIGINT UNSIGNED NOT NULL,
  contact_name_snapshot VARCHAR(64) NOT NULL,
  contact_phone_snapshot VARBINARY(16) NOT NULL,
  identity_kind ENUM('STAFF','VISITOR') NOT NULL,
  identity_source_version BIGINT UNSIGNED NOT NULL,
  discount_rate_percent TINYINT UNSIGNED NOT NULL,
  discount_version BIGINT UNSIGNED NOT NULL,
  store_name_snapshot TEXT NOT NULL,
  store_address_snapshot TEXT NOT NULL,
  pickup_point_snapshot TEXT NOT NULL,
  pickup_date DATE NOT NULL,
  pickup_time TIME NOT NULL,
  pickup_at TIMESTAMP(6) NOT NULL,
  meal_period ENUM('lunch','dinner') NOT NULL,
  order_note TEXT NOT NULL,
  item_count SMALLINT UNSIGNED NOT NULL,
  original_subtotal_cents BIGINT UNSIGNED NOT NULL,
  discount_cents BIGINT UNSIGNED NOT NULL,
  payable_cents BIGINT UNSIGNED NOT NULL,
  snapshot_digest BINARY(32) NOT NULL,
  transaction_id VARBINARY(64) NOT NULL,
  paid_at TIMESTAMP(6) NOT NULL,
  materialized_at TIMESTAMP(6) NOT NULL,
  pickup_number SMALLINT UNSIGNED NOT NULL,
  state ENUM('RESERVED','PREPARING','READY_FOR_PICKUP','COMPLETED','REFUNDING','REFUNDED') NOT NULL,
  preparing_at TIMESTAMP(6) NULL,
  ready_at TIMESTAMP(6) NULL,
  completed_at TIMESTAMP(6) NULL,
  refunding_at TIMESTAMP(6) NULL,
  refunded_at TIMESTAMP(6) NULL,
  redemption_token_ciphertext VARBINARY(192) NULL,
  redemption_token_hash BINARY(32) NULL,
  redemption_key_version SMALLINT UNSIGNED NULL,
  redemption_issued_at TIMESTAMP(6) NULL,
  redeemed_by_account_id BIGINT UNSIGNED NULL,
  redeemed_at TIMESTAMP(6) NULL,
  record_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_orders_order_no (order_no),
  UNIQUE KEY uq_orders_quote (quote_id),
  UNIQUE KEY uq_orders_prepayment (prepayment_id),
  UNIQUE KEY uq_orders_observation (payment_observation_id),
  UNIQUE KEY uq_orders_transaction (transaction_id),
  UNIQUE KEY uq_orders_pickup (pickup_date,pickup_number),
  UNIQUE KEY uq_orders_redemption_hash (redemption_token_hash),
  KEY idx_orders_state_pickup (state,pickup_at,id),
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES miniprogram_users (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_orders_quote FOREIGN KEY (quote_id) REFERENCES quotes (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_orders_prepayment FOREIGN KEY (prepayment_id) REFERENCES prepayments (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_orders_observation FOREIGN KEY (payment_observation_id) REFERENCES payment_observations (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_orders_redeemed_by FOREIGN KEY (redeemed_by_account_id) REFERENCES merchant_accounts (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_orders_snapshots CHECK (OCTET_LENGTH(order_no) BETWEEN 1 AND 64 AND CHAR_LENGTH(TRIM(contact_name_snapshot))>0 AND REGEXP_LIKE(CONVERT(contact_phone_snapshot USING ascii), '^\\+[1-9][0-9]{0,14}$', 'c') AND identity_source_version>0 AND discount_rate_percent BETWEEN 1 AND 100 AND discount_version>0 AND CHAR_LENGTH(TRIM(store_name_snapshot))>0 AND CHAR_LENGTH(TRIM(store_address_snapshot))>0 AND CHAR_LENGTH(TRIM(pickup_point_snapshot))>0 AND SECOND(pickup_time)=0 AND item_count>0 AND original_subtotal_cents=discount_cents+payable_cents AND payable_cents>0 AND OCTET_LENGTH(transaction_id) BETWEEN 1 AND 64 AND pickup_number BETWEEN 1 AND 9999),
  CONSTRAINT chk_orders_history CHECK (materialized_at>=paid_at AND updated_at>=created_at AND (preparing_at IS NULL OR preparing_at>=materialized_at) AND (ready_at IS NULL OR (preparing_at IS NOT NULL AND ready_at>=preparing_at)) AND (redemption_issued_at IS NULL OR (ready_at IS NOT NULL AND redemption_issued_at>=ready_at)) AND (redeemed_at IS NULL OR (redemption_issued_at IS NOT NULL AND redeemed_at>=redemption_issued_at)) AND (completed_at IS NULL OR (ready_at IS NOT NULL AND completed_at>=ready_at)) AND (refunding_at IS NULL OR refunding_at>=materialized_at) AND (refunded_at IS NULL OR (refunding_at IS NOT NULL AND refunded_at>=refunding_at))),
  CONSTRAINT chk_orders_state CHECK ((state='RESERVED' AND preparing_at IS NULL AND ready_at IS NULL AND completed_at IS NULL AND refunding_at IS NULL AND refunded_at IS NULL AND redemption_token_ciphertext IS NULL AND redemption_token_hash IS NULL AND redemption_key_version IS NULL AND redemption_issued_at IS NULL AND redeemed_by_account_id IS NULL AND redeemed_at IS NULL) OR (state='PREPARING' AND preparing_at IS NOT NULL AND ready_at IS NULL AND completed_at IS NULL AND refunding_at IS NULL AND refunded_at IS NULL AND redemption_token_ciphertext IS NULL AND redemption_token_hash IS NULL AND redemption_key_version IS NULL AND redemption_issued_at IS NULL AND redeemed_by_account_id IS NULL AND redeemed_at IS NULL) OR (state='READY_FOR_PICKUP' AND preparing_at IS NOT NULL AND ready_at IS NOT NULL AND completed_at IS NULL AND refunding_at IS NULL AND refunded_at IS NULL AND redemption_token_ciphertext IS NOT NULL AND redemption_token_hash IS NOT NULL AND redemption_key_version IS NOT NULL AND redemption_issued_at IS NOT NULL AND redeemed_by_account_id IS NULL AND redeemed_at IS NULL) OR (state='COMPLETED' AND preparing_at IS NOT NULL AND ready_at IS NOT NULL AND completed_at IS NOT NULL AND refunding_at IS NULL AND refunded_at IS NULL AND redemption_token_ciphertext IS NULL AND redemption_token_hash IS NOT NULL AND redemption_key_version IS NULL AND redemption_issued_at IS NOT NULL AND redeemed_by_account_id IS NOT NULL AND redeemed_at IS NOT NULL) OR (state='REFUNDING' AND refunding_at IS NOT NULL AND refunded_at IS NULL AND redemption_token_ciphertext IS NULL AND redemption_key_version IS NULL AND ((redemption_token_hash IS NULL AND redemption_issued_at IS NULL) OR (redemption_token_hash IS NOT NULL AND redemption_issued_at IS NOT NULL)) AND ((completed_at IS NULL AND redeemed_by_account_id IS NULL AND redeemed_at IS NULL) OR (completed_at IS NOT NULL AND redeemed_by_account_id IS NOT NULL AND redeemed_at IS NOT NULL))) OR (state='REFUNDED' AND refunding_at IS NOT NULL AND refunded_at IS NOT NULL AND redemption_token_ciphertext IS NULL AND redemption_key_version IS NULL AND ((redemption_token_hash IS NULL AND redemption_issued_at IS NULL) OR (redemption_token_hash IS NOT NULL AND redemption_issued_at IS NOT NULL)) AND ((completed_at IS NULL AND redeemed_by_account_id IS NULL AND redeemed_at IS NULL) OR (completed_at IS NOT NULL AND redeemed_by_account_id IS NOT NULL AND redeemed_at IS NOT NULL)))),
  CONSTRAINT chk_orders_record_version CHECK (record_version>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
