CREATE TABLE prepayments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  quote_id BIGINT UNSIGNED NOT NULL,
  idempotency_key_hash BINARY(32) NOT NULL,
  out_trade_no VARBINARY(64) NOT NULL,
  expected_appid VARBINARY(64) NOT NULL,
  expected_mchid VARBINARY(64) NOT NULL,
  expected_amount_cents BIGINT UNSIGNED NOT NULL,
  currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  provider_create_request_json JSON NOT NULL,
  provider_create_request_digest BINARY(32) NOT NULL,
  effective_deadline TIMESTAMP(6) NOT NULL,
  provider_state ENUM('READY','CREATE_CLAIMED','CREATE_UNKNOWN','PAYMENT_REQUESTED','NOT_PAID','PAID','CLOSED') NOT NULL,
  create_attempted_at TIMESTAMP(6) NULL,
  wx_request_payment_json JSON NULL,
  provider_prepay_id VARBINARY(128) NULL,
  last_queried_at TIMESTAMP(6) NULL,
  materialization_state ENUM('AWAITING_PAYMENT','READY','APPLIED','PENDING_MANUAL','REFUNDED_WITHOUT_ORDER') NOT NULL,
  pending_reason_code VARCHAR(64) NULL,
  materialized_at TIMESTAMP(6) NULL,
  lease_kind ENUM('CREATE','QUERY') NULL,
  lease_owner BINARY(16) NULL,
  lease_expires_at TIMESTAMP(6) NULL,
  record_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  next_reconcile_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_prepayments_quote (quote_id),
  UNIQUE KEY uq_prepayments_out_trade_no (out_trade_no),
  UNIQUE KEY uq_prepayments_user_idempotency (user_id,idempotency_key_hash),
  KEY idx_prepayments_next_reconcile (next_reconcile_at,id),
  CONSTRAINT fk_prepayments_user FOREIGN KEY (user_id) REFERENCES miniprogram_users (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_prepayments_quote FOREIGN KEY (quote_id) REFERENCES quotes (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_prepayments_immutable CHECK (OCTET_LENGTH(out_trade_no) BETWEEN 1 AND 64 AND OCTET_LENGTH(expected_appid) BETWEEN 1 AND 64 AND OCTET_LENGTH(expected_mchid) BETWEEN 1 AND 64 AND expected_amount_cents>0 AND currency='CNY' AND JSON_TYPE(provider_create_request_json)='OBJECT' AND effective_deadline>created_at),
  CONSTRAINT chk_prepayments_lease_group CHECK ((lease_kind IS NULL AND lease_owner IS NULL AND lease_expires_at IS NULL) OR (lease_kind IS NOT NULL AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)),
  CONSTRAINT chk_prepayments_provider_state CHECK ((provider_state='READY' AND create_attempted_at IS NULL AND provider_prepay_id IS NULL AND wx_request_payment_json IS NULL AND lease_kind IS NULL) OR (provider_state='CREATE_CLAIMED' AND create_attempted_at IS NOT NULL AND provider_prepay_id IS NULL AND wx_request_payment_json IS NULL AND lease_kind='CREATE') OR (provider_state='CREATE_UNKNOWN' AND create_attempted_at IS NOT NULL AND provider_prepay_id IS NULL AND wx_request_payment_json IS NULL AND (lease_kind IS NULL OR lease_kind='QUERY')) OR (provider_state='PAYMENT_REQUESTED' AND create_attempted_at IS NOT NULL AND provider_prepay_id IS NOT NULL AND wx_request_payment_json IS NOT NULL AND (lease_kind IS NULL OR lease_kind='QUERY')) OR (provider_state IN ('NOT_PAID','PAID','CLOSED') AND create_attempted_at IS NOT NULL AND ((provider_prepay_id IS NULL AND wx_request_payment_json IS NULL) OR (provider_prepay_id IS NOT NULL AND wx_request_payment_json IS NOT NULL)) AND (lease_kind IS NULL OR lease_kind='QUERY'))),
  CONSTRAINT chk_prepayments_materialization CHECK ((materialization_state IN ('AWAITING_PAYMENT','READY') AND pending_reason_code IS NULL AND materialized_at IS NULL) OR (materialization_state IN ('APPLIED','REFUNDED_WITHOUT_ORDER') AND pending_reason_code IS NULL AND materialized_at IS NOT NULL) OR (materialization_state='PENDING_MANUAL' AND pending_reason_code IS NOT NULL AND CHAR_LENGTH(TRIM(pending_reason_code))>0 AND materialized_at IS NULL)),
  CONSTRAINT chk_prepayments_record_version CHECK (record_version>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
