CREATE TABLE refund_observations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  refund_id BIGINT UNSIGNED NOT NULL,
  dedupe_key BINARY(32) NOT NULL,
  source ENUM('CALLBACK','ACTIVE_QUERY') NOT NULL,
  provider_event_id VARBINARY(128) NULL,
  out_refund_no VARBINARY(64) NOT NULL,
  provider_refund_id VARBINARY(128) NULL,
  provider_state ENUM('PROCESSING','SUCCESS','CLOSED') NOT NULL,
  validation ENUM('MATCH','MISMATCH') NOT NULL,
  mismatch_code VARCHAR(64) NULL,
  success_time TIMESTAMP(6) NULL,
  received_at TIMESTAMP(6) NOT NULL,
  apply_state ENUM('NEW','APPLIED','DEFERRED') NOT NULL,
  apply_reason_code VARCHAR(64) NULL,
  applied_at TIMESTAMP(6) NULL,
  record_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_refund_observations_dedupe (dedupe_key),
  CONSTRAINT fk_refund_observations_refund FOREIGN KEY (refund_id) REFERENCES refunds (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_refund_observations_identity CHECK (OCTET_LENGTH(out_refund_no) BETWEEN 1 AND 64 AND (provider_event_id IS NULL OR OCTET_LENGTH(provider_event_id) BETWEEN 1 AND 128) AND (provider_refund_id IS NULL OR OCTET_LENGTH(provider_refund_id) BETWEEN 1 AND 128)),
  CONSTRAINT chk_refund_observations_validation CHECK ((validation='MATCH' AND mismatch_code IS NULL) OR (validation='MISMATCH' AND mismatch_code IS NOT NULL AND CHAR_LENGTH(TRIM(mismatch_code))>0)),
  CONSTRAINT chk_refund_observations_success CHECK ((provider_state='SUCCESS' AND provider_refund_id IS NOT NULL AND success_time IS NOT NULL) OR (provider_state IN ('PROCESSING','CLOSED') AND success_time IS NULL)),
  CONSTRAINT chk_refund_observations_apply CHECK ((apply_state='NEW' AND apply_reason_code IS NULL AND applied_at IS NULL) OR (apply_state='APPLIED' AND apply_reason_code IS NULL AND applied_at IS NOT NULL) OR (apply_state='DEFERRED' AND apply_reason_code IS NOT NULL AND CHAR_LENGTH(TRIM(apply_reason_code))>0 AND applied_at IS NULL)),
  CONSTRAINT chk_refund_observations_record_version CHECK (record_version>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
