CREATE TABLE IF NOT EXISTS schema_migrations (
  version BIGINT UNSIGNED PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  checksum BINARY(32) NOT NULL,
  dirty BOOLEAN NOT NULL,
  applied_at TIMESTAMP(6) NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
