ALTER TABLE action_audits
  DROP FOREIGN KEY fk_merchant_action_audits_account,
  DROP INDEX idx_merchant_action_audits_account_time,
  DROP INDEX idx_merchant_action_audits_actor_time,
  DROP CHECK chk_merchant_action_audits_snapshot,
  DROP CHECK chk_merchant_action_audits_target,
  DROP CHECK chk_merchant_action_audits_actor,
  DROP CHECK chk_merchant_action_audits_text,
  RENAME COLUMN merchant_account_id TO actor_account_id,
  RENAME COLUMN account_id_snapshot TO actor_account_id_snapshot,
  RENAME COLUMN role_snapshot TO actor_role_snapshot,
  RENAME COLUMN auth_version_snapshot TO actor_auth_version_snapshot,
  RENAME COLUMN reason TO reason_code,
  RENAME COLUMN idempotency_key_hash TO operation_key_hash,
  MODIFY COLUMN actor_user_id BIGINT UNSIGNED NULL,
  ADD COLUMN entry_kind ENUM('LEGACY_EVIDENCE','COMMAND_RECEIPT','SYSTEM_EVIDENCE') NULL AFTER id,
  ADD COLUMN actor_kind ENUM('USER','MERCHANT','SYSTEM','PROVIDER') NULL AFTER entry_kind,
  ADD COLUMN actor_scope_hash BINARY(32) NULL AFTER actor_kind,
  ADD COLUMN target_key_hash BINARY(32) NULL AFTER target_id,
  ADD COLUMN request_id_hash BINARY(32) NULL AFTER request_id,
  ADD COLUMN before_state_json JSON NULL AFTER state_before,
  ADD COLUMN after_state_json JSON NULL AFTER state_after,
  ADD COLUMN response_json JSON NULL AFTER after_state_json;
