CREATE TABLE notification_outbox (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  consent_id BIGINT UNSIGNED NOT NULL,
  kind ENUM('READY','REFUND_RESULT') NOT NULL,
  recipient_user_id BIGINT UNSIGNED NOT NULL,
  immutable_message_json JSON NOT NULL,
  template_config_version BIGINT UNSIGNED NOT NULL,
  state ENUM('PENDING','IN_FLIGHT','SENT','FAILED_PERMANENT') NOT NULL,
  attempt_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMP(6) NULL,
  lease_owner BINARY(16) NULL,
  lease_expires_at TIMESTAMP(6) NULL,
  record_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  provider_message_id VARBINARY(128) NULL,
  last_error_code VARCHAR(64) NULL,
  created_at TIMESTAMP(6) NOT NULL,
  sent_at TIMESTAMP(6) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_notification_outbox_consent (consent_id),
  UNIQUE KEY uq_notification_outbox_order_kind (order_id,kind),
  KEY idx_notification_outbox_due (state,next_attempt_at,id),
  CONSTRAINT fk_notification_outbox_order FOREIGN KEY (order_id) REFERENCES orders (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_notification_outbox_consent FOREIGN KEY (consent_id) REFERENCES notification_consents (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_notification_outbox_user FOREIGN KEY (recipient_user_id) REFERENCES miniprogram_users (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_notification_outbox_values CHECK (JSON_TYPE(immutable_message_json)='OBJECT' AND template_config_version>0 AND record_version>0),
  CONSTRAINT chk_notification_outbox_state CHECK ((state='PENDING' AND next_attempt_at IS NOT NULL AND lease_owner IS NULL AND lease_expires_at IS NULL AND sent_at IS NULL AND provider_message_id IS NULL) OR (state='IN_FLIGHT' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL AND sent_at IS NULL AND provider_message_id IS NULL) OR (state='SENT' AND sent_at IS NOT NULL AND lease_owner IS NULL AND lease_expires_at IS NULL AND last_error_code IS NULL) OR (state='FAILED_PERMANENT' AND last_error_code IS NOT NULL AND CHAR_LENGTH(TRIM(last_error_code))>0 AND lease_owner IS NULL AND lease_expires_at IS NULL AND sent_at IS NULL AND provider_message_id IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
