CREATE TABLE refunds (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  prepayment_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NULL,
  out_refund_no VARBINARY(64) NOT NULL,
  idempotency_key_hash BINARY(32) NOT NULL,
  amount_cents BIGINT UNSIGNED NOT NULL,
  currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  reason_code VARCHAR(64) NOT NULL,
  requested_by_user_id BIGINT UNSIGNED NULL,
  requested_by_account_id BIGINT UNSIGNED NULL,
  provider_request_json JSON NOT NULL,
  provider_request_digest BINARY(32) NOT NULL,
  provider_state ENUM('READY','CREATE_CLAIMED','CREATE_UNKNOWN','PROCESSING','SUCCESS','CLOSED') NOT NULL,
  create_attempted_at TIMESTAMP(6) NULL,
  provider_refund_id VARBINARY(128) NULL,
  materialization_state ENUM('AWAITING_PROVIDER','APPLIED','PENDING_MANUAL') NOT NULL,
  pending_reason_code VARCHAR(64) NULL,
  materialized_at TIMESTAMP(6) NULL,
  lease_kind ENUM('CREATE','QUERY') NULL,
  lease_owner BINARY(16) NULL,
  lease_expires_at TIMESTAMP(6) NULL,
  record_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  next_query_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_refunds_prepayment (prepayment_id),
  UNIQUE KEY uq_refunds_order (order_id),
  UNIQUE KEY uq_refunds_out_refund_no (out_refund_no),
  CONSTRAINT fk_refunds_prepayment FOREIGN KEY (prepayment_id) REFERENCES prepayments (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_refunds_order FOREIGN KEY (order_id) REFERENCES orders (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_refunds_requested_user FOREIGN KEY (requested_by_user_id) REFERENCES miniprogram_users (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_refunds_requested_account FOREIGN KEY (requested_by_account_id) REFERENCES merchant_accounts (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_refunds_immutable CHECK (OCTET_LENGTH(out_refund_no) BETWEEN 1 AND 64 AND amount_cents>0 AND currency='CNY' AND CHAR_LENGTH(TRIM(reason_code))>0 AND ((requested_by_user_id IS NOT NULL AND requested_by_account_id IS NULL) OR (requested_by_user_id IS NULL AND requested_by_account_id IS NOT NULL)) AND JSON_TYPE(provider_request_json)='OBJECT'),
  CONSTRAINT chk_refunds_lease_group CHECK ((lease_kind IS NULL AND lease_owner IS NULL AND lease_expires_at IS NULL) OR (lease_kind IS NOT NULL AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)),
  CONSTRAINT chk_refunds_provider_state CHECK ((provider_state='READY' AND create_attempted_at IS NULL AND provider_refund_id IS NULL AND lease_kind IS NULL) OR (provider_state='CREATE_CLAIMED' AND create_attempted_at IS NOT NULL AND provider_refund_id IS NULL AND lease_kind='CREATE') OR (provider_state='CREATE_UNKNOWN' AND create_attempted_at IS NOT NULL AND provider_refund_id IS NULL AND (lease_kind IS NULL OR lease_kind='QUERY')) OR (provider_state IN ('PROCESSING','SUCCESS','CLOSED') AND create_attempted_at IS NOT NULL AND provider_refund_id IS NOT NULL AND (lease_kind IS NULL OR lease_kind='QUERY'))),
  CONSTRAINT chk_refunds_materialization CHECK ((materialization_state='AWAITING_PROVIDER' AND pending_reason_code IS NULL AND materialized_at IS NULL) OR (materialization_state='APPLIED' AND pending_reason_code IS NULL AND materialized_at IS NOT NULL) OR (materialization_state='PENDING_MANUAL' AND pending_reason_code IS NOT NULL AND CHAR_LENGTH(TRIM(pending_reason_code))>0 AND materialized_at IS NULL)),
  CONSTRAINT chk_refunds_record_version CHECK (record_version>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
