CREATE TABLE merchant_pc_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  approval_secret_hash BINARY(32) NOT NULL,
  poll_secret_hash BINARY(32) NOT NULL,
  state ENUM('WAITING','APPROVED','CONSUMED') NOT NULL,
  login_expires_at TIMESTAMP(6) NOT NULL,
  approved_account_id BIGINT UNSIGNED NULL,
  approved_user_id BIGINT UNSIGNED NULL,
  approved_auth_version BIGINT UNSIGNED NULL,
  approved_at TIMESTAMP(6) NULL,
  consumed_at TIMESTAMP(6) NULL,
  access_token_hash BINARY(32) NULL,
  access_issued_at TIMESTAMP(6) NULL,
  access_expires_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_merchant_pc_sessions_approval_secret (approval_secret_hash),
  UNIQUE KEY uq_merchant_pc_sessions_poll_secret (poll_secret_hash),
  UNIQUE KEY uq_merchant_pc_sessions_access_token (access_token_hash),
  CONSTRAINT fk_merchant_pc_sessions_account FOREIGN KEY (approved_account_id) REFERENCES merchant_accounts (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_pc_sessions_user FOREIGN KEY (approved_user_id) REFERENCES miniprogram_users (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_merchant_pc_sessions_login_expiry CHECK (login_expires_at=TIMESTAMPADD(MINUTE,2,created_at)),
  CONSTRAINT chk_merchant_pc_sessions_state CHECK ((state='WAITING' AND approved_account_id IS NULL AND approved_user_id IS NULL AND approved_auth_version IS NULL AND approved_at IS NULL AND consumed_at IS NULL AND access_token_hash IS NULL AND access_issued_at IS NULL AND access_expires_at IS NULL) OR (state='APPROVED' AND approved_account_id IS NOT NULL AND approved_user_id IS NOT NULL AND approved_auth_version IS NOT NULL AND approved_at IS NOT NULL AND approved_at BETWEEN created_at AND login_expires_at AND consumed_at IS NULL AND access_token_hash IS NULL AND access_issued_at IS NULL AND access_expires_at IS NULL) OR (state='CONSUMED' AND approved_account_id IS NOT NULL AND approved_user_id IS NOT NULL AND approved_auth_version IS NOT NULL AND approved_at IS NOT NULL AND approved_at BETWEEN created_at AND login_expires_at AND consumed_at IS NOT NULL AND consumed_at BETWEEN approved_at AND login_expires_at AND access_token_hash IS NOT NULL AND access_issued_at IS NOT NULL AND access_issued_at>=consumed_at AND access_expires_at IS NOT NULL AND access_expires_at=TIMESTAMPADD(HOUR,12,access_issued_at))),
  CONSTRAINT chk_merchant_pc_sessions_updated CHECK (updated_at>=created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
