CREATE TABLE quote_items (
  quote_id BIGINT UNSIGNED NOT NULL,
  line_number SMALLINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  product_name_snapshot TEXT NOT NULL,
  product_source_version BINARY(32) NOT NULL,
  image_object_key_snapshot VARBINARY(1024) NULL,
  original_unit_price_cents BIGINT UNSIGNED NOT NULL,
  discounted_unit_price_cents BIGINT UNSIGNED NOT NULL,
  quantity BIGINT UNSIGNED NOT NULL,
  original_subtotal_cents BIGINT UNSIGNED NOT NULL,
  payable_subtotal_cents BIGINT UNSIGNED NOT NULL,
  flavors_json JSON NOT NULL,
  line_note TEXT NOT NULL,
  PRIMARY KEY (quote_id, line_number),
  CONSTRAINT fk_quote_items_quote FOREIGN KEY (quote_id) REFERENCES quotes (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_quote_items_line_number CHECK (line_number > 0),
  CONSTRAINT chk_quote_items_product_name CHECK (CHAR_LENGTH(TRIM(product_name_snapshot)) > 0),
  CONSTRAINT chk_quote_items_image_key CHECK (image_object_key_snapshot IS NULL OR OCTET_LENGTH(image_object_key_snapshot) BETWEEN 1 AND 1024),
  CONSTRAINT chk_quote_items_prices CHECK (discounted_unit_price_cents <= original_unit_price_cents),
  CONSTRAINT chk_quote_items_quantity CHECK (quantity > 0),
  CONSTRAINT chk_quote_items_original_subtotal CHECK (original_subtotal_cents = original_unit_price_cents * quantity),
  CONSTRAINT chk_quote_items_payable_subtotal CHECK (payable_subtotal_cents = discounted_unit_price_cents * quantity),
  CONSTRAINT chk_quote_items_flavors CHECK (JSON_TYPE(flavors_json) = 'ARRAY')
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
