CREATE TABLE payment_observations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  prepayment_id BIGINT UNSIGNED NOT NULL,
  dedupe_key BINARY(32) NOT NULL,
  source ENUM('CALLBACK','ACTIVE_QUERY') NOT NULL,
  provider_event_id VARBINARY(128) NULL,
  out_trade_no VARBINARY(64) NOT NULL,
  transaction_id VARBINARY(64) NULL,
  provider_state ENUM('PAID','NOT_PAID','CLOSED') NOT NULL,
  validation ENUM('MATCH','MISMATCH') NOT NULL,
  mismatch_code VARCHAR(64) NULL,
  amount_cents BIGINT UNSIGNED NULL,
  currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NULL,
  success_time TIMESTAMP(6) NULL,
  received_at TIMESTAMP(6) NOT NULL,
  materialization_mode ENUM('AUTO','DELAYED_MANUAL') NOT NULL,
  apply_state ENUM('NEW','APPLIED','DEFERRED') NOT NULL,
  apply_reason_code VARCHAR(64) NULL,
  applied_at TIMESTAMP(6) NULL,
  record_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_payment_observations_dedupe (dedupe_key),
  UNIQUE KEY uq_payment_observations_transaction (transaction_id),
  CONSTRAINT fk_payment_observations_prepayment FOREIGN KEY (prepayment_id) REFERENCES prepayments (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_payment_observations_identity CHECK (OCTET_LENGTH(out_trade_no) BETWEEN 1 AND 64 AND (provider_event_id IS NULL OR OCTET_LENGTH(provider_event_id) BETWEEN 1 AND 128)),
  CONSTRAINT chk_payment_observations_validation CHECK ((validation='MATCH' AND mismatch_code IS NULL) OR (validation='MISMATCH' AND mismatch_code IS NOT NULL AND CHAR_LENGTH(TRIM(mismatch_code))>0)),
  CONSTRAINT chk_payment_observations_payment CHECK ((provider_state='PAID' AND transaction_id IS NOT NULL AND amount_cents IS NOT NULL AND currency IS NOT NULL AND success_time IS NOT NULL) OR (provider_state IN ('NOT_PAID','CLOSED') AND transaction_id IS NULL AND success_time IS NULL)),
  CONSTRAINT chk_payment_observations_auto CHECK (materialization_mode<>'AUTO' OR (validation='MATCH' AND provider_state='PAID' AND success_time IS NOT NULL)),
  CONSTRAINT chk_payment_observations_apply CHECK ((apply_state='NEW' AND apply_reason_code IS NULL AND applied_at IS NULL) OR (apply_state='APPLIED' AND apply_reason_code IS NULL AND applied_at IS NOT NULL) OR (apply_state='DEFERRED' AND apply_reason_code IS NOT NULL AND CHAR_LENGTH(TRIM(apply_reason_code))>0 AND applied_at IS NULL)),
  CONSTRAINT chk_payment_observations_record_version CHECK (record_version>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
