CREATE TABLE import_batches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  kind ENUM('PRODUCT','STAFF') NOT NULL,
  actor_account_id BIGINT UNSIGNED NOT NULL,
  file_object_key VARBINARY(1024) NULL,
  file_digest BINARY(32) NOT NULL,
  file_size_bytes BIGINT UNSIGNED NOT NULL,
  row_count INT UNSIGNED NOT NULL,
  preview_token_hash BINARY(32) NOT NULL,
  preview_json JSON NULL,
  new_count INT UNSIGNED NOT NULL,
  update_count INT UNSIGNED NOT NULL,
  error_count INT UNSIGNED NOT NULL,
  state ENUM('PREVIEWED','COMMITTED','EXPIRED') NOT NULL,
  commit_idempotency_key_hash BINARY(32) NULL,
  skip_invalid BOOLEAN NULL,
  result_json JSON NULL,
  expires_at TIMESTAMP(6) NOT NULL,
  committed_at TIMESTAMP(6) NULL,
  record_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_import_batches_preview_token (preview_token_hash),
  UNIQUE KEY uq_import_batches_commit (actor_account_id,commit_idempotency_key_hash),
  CONSTRAINT fk_import_batches_actor FOREIGN KEY (actor_account_id) REFERENCES merchant_accounts (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_import_batches_file CHECK ((file_object_key IS NULL OR OCTET_LENGTH(file_object_key) BETWEEN 1 AND 1024) AND file_size_bytes BETWEEN 1 AND 10485760 AND ((kind='PRODUCT' AND row_count BETWEEN 1 AND 500) OR (kind='STAFF' AND row_count BETWEEN 1 AND 5000)) AND new_count+update_count+error_count=row_count),
  CONSTRAINT chk_import_batches_state CHECK ((state='PREVIEWED' AND preview_json IS NOT NULL AND commit_idempotency_key_hash IS NULL AND skip_invalid IS NULL AND result_json IS NULL AND committed_at IS NULL AND expires_at>created_at) OR (state='COMMITTED' AND commit_idempotency_key_hash IS NOT NULL AND skip_invalid IS NOT NULL AND result_json IS NOT NULL AND committed_at IS NOT NULL AND committed_at<=expires_at AND (kind<>'STAFF' OR preview_json IS NULL)) OR (state='EXPIRED' AND preview_json IS NULL AND commit_idempotency_key_hash IS NULL AND skip_invalid IS NULL AND result_json IS NULL AND committed_at IS NULL)),
  CONSTRAINT chk_import_batches_record_version CHECK (record_version>0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
